const { google } = require('googleapis');
const fs = require('fs');

const creds = JSON.parse(fs.readFileSync('./oauth-credentials.json'));
const { client_id, client_secret } = creds.installed;
const tokens = JSON.parse(fs.readFileSync('./oauth-token.json'));

const oauth2Client = new google.auth.OAuth2(client_id, client_secret, 'http://localhost:3000');
oauth2Client.setCredentials(tokens);

const indexing = google.indexing({ version: 'v3', auth: oauth2Client });

const urls = [
'https://blog.becgrowth.com/blog/cold-email-hyperise-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-vidyard-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-sendspark-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-gan-ai-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-pitch-ai-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-amplemarket-guide',
'https://blog.becgrowth.com/blog/cold-email-apollo-io-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-zoominfo-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-lusha-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-clearbit-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-bombora-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-6sense-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-demandbase-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-g2-intent-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-linkedin-sales-nav-guide',
'https://blog.becgrowth.com/blog/cold-email-phantombuster-guide',
'https://blog.becgrowth.com/blog/cold-email-evaboot-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-walaxy-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-expandi-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-dripify-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-octopus-crm-guide',
'https://blog.becgrowth.com/blog/cold-email-skylead-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-meet-alfred-guide',
'https://blog.becgrowth.com/blog/cold-email-linked-helper-guide',
'https://blog.becgrowth.com/blog/cold-email-zopto-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-offer-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-offer-creation-guide',
'https://blog.becgrowth.com/blog/cold-email-offer-positioning-guide',
'https://blog.becgrowth.com/blog/cold-email-offer-testing-guide',
'https://blog.becgrowth.com/blog/cold-email-offer-optimization-guide',
'https://blog.becgrowth.com/blog/cold-email-irresistible-offer-guide',
'https://blog.becgrowth.com/blog/cold-email-high-ticket-offer-guide',
'https://blog.becgrowth.com/blog/cold-email-productized-offer-guide',
'https://blog.becgrowth.com/blog/cold-email-retainer-offer-guide',
'https://blog.becgrowth.com/blog/cold-email-performance-offer-guide',
'https://blog.becgrowth.com/blog/cold-email-guarantee-offer-guide',
'https://blog.becgrowth.com/blog/cold-email-free-trial-offer-guide',
'https://blog.becgrowth.com/blog/cold-email-risk-reversal-guide',
'https://blog.becgrowth.com/blog/cold-email-pricing-strategy-guide',
'https://blog.becgrowth.com/blog/cold-email-pricing-psychology-guide',
'https://blog.becgrowth.com/blog/cold-email-niche-offer-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-vertical-offer-guide',
'https://blog.becgrowth.com/blog/cold-email-horizontal-offer-guide',
'https://blog.becgrowth.com/blog/cold-email-done-for-you-offer-guide',
'https://blog.becgrowth.com/blog/cold-email-done-with-you-offer-guide',
'https://blog.becgrowth.com/blog/cold-email-do-it-yourself-offer-guide',
'https://blog.becgrowth.com/blog/cold-email-saas-offer-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-agency-offer-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-consulting-offer-guide',
'https://blog.becgrowth.com/blog/cold-email-coaching-offer-guide',
'https://blog.becgrowth.com/blog/cold-email-b2b-icp-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-icp-research-guide',
'https://blog.becgrowth.com/blog/cold-email-icp-validation-guide',
'https://blog.becgrowth.com/blog/cold-email-icp-refinement-guide',
'https://blog.becgrowth.com/blog/cold-email-icp-expansion-guide',
'https://blog.becgrowth.com/blog/cold-email-market-entry-guide',
'https://blog.becgrowth.com/blog/cold-email-market-expansion-guide',
'https://blog.becgrowth.com/blog/cold-email-new-market-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-competitive-market-guide',
'https://blog.becgrowth.com/blog/cold-email-saturated-market-guide',
'https://blog.becgrowth.com/blog/cold-email-emerging-market-guide',
'https://blog.becgrowth.com/blog/cold-email-niche-market-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-b2b-us-market-2026',
'https://blog.becgrowth.com/blog/cold-email-b2b-uk-market-2026',
'https://blog.becgrowth.com/blog/cold-email-b2b-canada-market-2026',
'https://blog.becgrowth.com/blog/cold-email-b2b-australia-market',
'https://blog.becgrowth.com/blog/cold-email-b2b-europe-market-2026',
'https://blog.becgrowth.com/blog/cold-email-b2b-germany-market',
'https://blog.becgrowth.com/blog/cold-email-b2b-france-market',
'https://blog.becgrowth.com/blog/cold-email-b2b-netherlands-market',
'https://blog.becgrowth.com/blog/cold-email-b2b-spain-market',
'https://blog.becgrowth.com/blog/cold-email-b2b-italy-market',
'https://blog.becgrowth.com/blog/cold-email-b2b-sweden-market',
'https://blog.becgrowth.com/blog/cold-email-b2b-denmark-market',
'https://blog.becgrowth.com/blog/cold-email-b2b-norway-market',
'https://blog.becgrowth.com/blog/cold-email-b2b-finland-market',
'https://blog.becgrowth.com/blog/cold-email-b2b-poland-market',
'https://blog.becgrowth.com/blog/cold-email-b2b-uae-market',
'https://blog.becgrowth.com/blog/cold-email-b2b-dubai-market',
'https://blog.becgrowth.com/blog/cold-email-b2b-saudi-arabia-market',
'https://blog.becgrowth.com/blog/cold-email-b2b-singapore-market',
'https://blog.becgrowth.com/blog/cold-email-b2b-india-market-2026',
'https://blog.becgrowth.com/blog/cold-email-b2b-israel-market',
'https://blog.becgrowth.com/blog/cold-email-b2b-south-africa-market',
'https://blog.becgrowth.com/blog/cold-email-b2b-nigeria-market',
'https://blog.becgrowth.com/blog/cold-email-b2b-brazil-market',
'https://blog.becgrowth.com/blog/cold-email-b2b-mexico-market',
'https://blog.becgrowth.com/blog/cold-email-b2b-argentina-market',
'https://blog.becgrowth.com/blog/cold-email-b2b-colombia-market',
'https://blog.becgrowth.com/blog/cold-email-b2b-chile-market',
'https://blog.becgrowth.com/blog/cold-email-b2b-japan-market',
'https://blog.becgrowth.com/blog/cold-email-b2b-south-korea-market',
'https://blog.becgrowth.com/blog/cold-email-b2b-china-market-2026',
'https://blog.becgrowth.com/blog/cold-email-b2b-new-zealand-market',
'https://blog.becgrowth.com/blog/cold-email-b2b-ireland-market',
'https://blog.becgrowth.com/blog/cold-email-b2b-switzerland-market',
'https://blog.becgrowth.com/blog/cold-email-revenue-model-guide',
'https://blog.becgrowth.com/blog/cold-email-mrr-growth-guide',
'https://blog.becgrowth.com/blog/cold-email-arr-growth-guide',
'https://blog.becgrowth.com/blog/cold-email-ltv-optimization-guide',
'https://blog.becgrowth.com/blog/cold-email-churn-reduction-guide',
'https://blog.becgrowth.com/blog/cold-email-expansion-revenue-guide',
'https://blog.becgrowth.com/blog/cold-email-net-revenue-retention',
'https://blog.becgrowth.com/blog/cold-email-gross-revenue-retention',
'https://blog.becgrowth.com/blog/cold-email-payback-period-guide',
'https://blog.becgrowth.com/blog/cold-email-unit-economics-guide',
'https://blog.becgrowth.com/blog/cold-email-profit-margin-guide',
'https://blog.becgrowth.com/blog/cold-email-cash-flow-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-bootstrapping-guide',
'https://blog.becgrowth.com/blog/cold-email-fundraising-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-vc-fundraising-guide',
'https://blog.becgrowth.com/blog/cold-email-angel-fundraising-guide',
'https://blog.becgrowth.com/blog/cold-email-crowdfunding-guide',
'https://blog.becgrowth.com/blog/cold-email-grants-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-for-startup-founders',
'https://blog.becgrowth.com/blog/cold-email-for-solo-founders',
'https://blog.becgrowth.com/blog/cold-email-for-co-founders',
'https://blog.becgrowth.com/blog/cold-email-for-technical-founders',
'https://blog.becgrowth.com/blog/cold-email-for-non-technical-founders',
'https://blog.becgrowth.com/blog/cold-email-for-first-time-founders',
'https://blog.becgrowth.com/blog/cold-email-for-serial-founders',
'https://blog.becgrowth.com/blog/cold-email-for-female-founders',
'https://blog.becgrowth.com/blog/cold-email-for-young-founders',
'https://blog.becgrowth.com/blog/cold-email-for-remote-founders',
'https://blog.becgrowth.com/blog/cold-email-for-immigrant-founders',
'https://blog.becgrowth.com/blog/cold-email-for-agency-founders',
'https://blog.becgrowth.com/blog/cold-email-for-saas-founders-2026',
'https://blog.becgrowth.com/blog/cold-email-for-consulting-founders',
'https://blog.becgrowth.com/blog/cold-email-for-coaching-founders',
'https://blog.becgrowth.com/blog/cold-email-for-ecommerce-founders',
'https://blog.becgrowth.com/blog/cold-email-for-media-founders',
'https://blog.becgrowth.com/blog/cold-email-for-fintech-founders',
'https://blog.becgrowth.com/blog/cold-email-for-healthtech-founders',
'https://blog.becgrowth.com/blog/cold-email-for-edtech-founders',
'https://blog.becgrowth.com/blog/cold-email-for-proptech-founders',
'https://blog.becgrowth.com/blog/cold-email-for-legaltech-founders',
'https://blog.becgrowth.com/blog/cold-email-for-hrtech-founders',
'https://blog.becgrowth.com/blog/cold-email-for-martech-founders',
'https://blog.becgrowth.com/blog/cold-email-for-adtech-founders',
'https://blog.becgrowth.com/blog/cold-email-for-cleantech-founders',
'https://blog.becgrowth.com/blog/cold-email-for-biotech-founders',
'https://blog.becgrowth.com/blog/cold-email-for-deeptech-founders',
'https://blog.becgrowth.com/blog/cold-email-for-ai-founders-2026',
'https://blog.becgrowth.com/blog/cold-email-for-web3-founders',
'https://blog.becgrowth.com/blog/cold-email-for-crypto-founders',
'https://blog.becgrowth.com/blog/cold-email-for-nft-founders',
'https://blog.becgrowth.com/blog/cold-email-for-defi-founders',
'https://blog.becgrowth.com/blog/cold-email-for-gaming-founders',
'https://blog.becgrowth.com/blog/cold-email-for-creator-economy-founders',
'https://blog.becgrowth.com/blog/cold-email-for-marketplace-founders',
'https://blog.becgrowth.com/blog/cold-email-for-platform-founders',
'https://blog.becgrowth.com/blog/cold-email-for-infrastructure-founders',
'https://blog.becgrowth.com/blog/cold-email-for-developer-tool-founders',
'https://blog.becgrowth.com/blog/cold-email-for-api-first-founders',
'https://blog.becgrowth.com/blog/cold-email-for-vertical-saas-founders',
'https://blog.becgrowth.com/blog/cold-email-for-horizontal-saas-founders',
'https://blog.becgrowth.com/blog/cold-email-for-enterprise-saas-founders',
'https://blog.becgrowth.com/blog/cold-email-for-smb-saas-founders',
'https://blog.becgrowth.com/blog/cold-email-for-plg-saas-founders',
'https://blog.becgrowth.com/blog/cold-email-for-slg-saas-founders',
'https://blog.becgrowth.com/blog/cold-email-10x-revenue-guide',
'https://blog.becgrowth.com/blog/cold-email-double-revenue-guide',
'https://blog.becgrowth.com/blog/cold-email-triple-revenue-guide',
'https://blog.becgrowth.com/blog/cold-email-100k-revenue-guide',
'https://blog.becgrowth.com/blog/cold-email-1m-revenue-guide',
'https://blog.becgrowth.com/blog/cold-email-10m-revenue-guide',
'https://blog.becgrowth.com/blog/cold-email-first-client-guide',
'https://blog.becgrowth.com/blog/cold-email-first-10-clients-guide',
'https://blog.becgrowth.com/blog/cold-email-first-100-clients-guide',
'https://blog.becgrowth.com/blog/cold-email-scale-to-1000-clients',
'https://blog.becgrowth.com/blog/cold-email-0-to-10k-mrr-guide',
'https://blog.becgrowth.com/blog/cold-email-10k-to-100k-mrr-guide',
'https://blog.becgrowth.com/blog/cold-email-100k-to-1m-mrr-guide',
'https://blog.becgrowth.com/blog/cold-email-growth-stages-guide',
'https://blog.becgrowth.com/blog/cold-email-pre-revenue-guide',
'https://blog.becgrowth.com/blog/cold-email-early-stage-guide',
'https://blog.becgrowth.com/blog/cold-email-growth-stage-guide',
'https://blog.becgrowth.com/blog/cold-email-scale-stage-guide',
'https://blog.becgrowth.com/blog/cold-email-mature-stage-guide',
'https://blog.becgrowth.com/blog/cold-email-hypergrowth-guide',
'https://blog.becgrowth.com/blog/cold-email-series-a-growth-guide',
'https://blog.becgrowth.com/blog/cold-email-series-b-growth-guide',
'https://blog.becgrowth.com/blog/cold-email-series-c-growth-guide',
'https://blog.becgrowth.com/blog/cold-email-ipo-readiness-guide',
'https://blog.becgrowth.com/blog/cold-email-acquisition-readiness-guide',
'https://blog.becgrowth.com/blog/cold-email-exit-strategy-guide',
'https://blog.becgrowth.com/blog/how-bec-growth-signs-clients',
'https://blog.becgrowth.com/blog/bec-growth-system-explained',
'https://blog.becgrowth.com/blog/bec-growth-results-explained',
'https://blog.becgrowth.com/blog/bec-growth-process-explained',
'https://blog.becgrowth.com/blog/bec-growth-approach-explained',
'https://blog.becgrowth.com/blog/bec-growth-difference-explained',
'https://blog.becgrowth.com/blog/bec-growth-story-explained',
'https://blog.becgrowth.com/blog/bec-growth-team-explained',
'https://blog.becgrowth.com/blog/bec-growth-values-explained',
'https://blog.becgrowth.com/blog/bec-growth-mission-explained',
'https://blog.becgrowth.com/blog/bec-growth-vision-explained',
];

async function submitUrls() {
  let success = 0, failed = 0;
  console.log(`\nSubmitting ${urls.length} URLs...\n`);
  for (let i = 0; i < urls.length; i++) {
    const url = urls[i];
    try {
      await indexing.urlNotifications.publish({
        requestBody: { url, type: 'URL_UPDATED' },
      });
      success++;
      console.log(`✓ [${i+1}/${urls.length}] ${url}`);
    } catch (err) {
      failed++;
      console.log(`✕ [${i+1}/${urls.length}] ${url} - ${err.response?.data?.error?.message || err.message}`);
    }
    await new Promise(r => setTimeout(r, 300));
  }
  console.log(`\nDone! Success: ${success}, Failed: ${failed}`);
}

submitUrls().catch(console.error);