const { google } = require('googleapis');
const fs = require('fs');

const creds = JSON.parse(fs.readFileSync('./oauth-credentials.json'));
const { client_id, client_secret } = creds.installed;
const tokens = JSON.parse(fs.readFileSync('./oauth-token.json'));

const oauth2Client = new google.auth.OAuth2(client_id, client_secret, 'http://localhost:3000');
oauth2Client.setCredentials(tokens);

const indexing = google.indexing({ version: 'v3', auth: oauth2Client });

const urls = [
'https://blog.becgrowth.com/blog/cold-email-for-b2b-growth-hacking-2026',
'https://blog.becgrowth.com/blog/cold-email-growth-hacking-strategies',
'https://blog.becgrowth.com/blog/cold-email-growth-hacking-tips-2026',
'https://blog.becgrowth.com/blog/cold-email-growth-hacking-tools',
'https://blog.becgrowth.com/blog/cold-email-growth-hacking-examples',
'https://blog.becgrowth.com/blog/cold-email-growth-hacking-mistakes',
'https://blog.becgrowth.com/blog/cold-email-growth-hacking-for-saas',
'https://blog.becgrowth.com/blog/cold-email-growth-hacking-for-agencies',
'https://blog.becgrowth.com/blog/cold-email-growth-hacking-for-startups',
'https://blog.becgrowth.com/blog/cold-email-growth-hacking-for-founders',
'https://blog.becgrowth.com/blog/cold-email-vs-inbound-marketing-b2b',
'https://blog.becgrowth.com/blog/cold-email-vs-outbound-marketing-b2b',
'https://blog.becgrowth.com/blog/cold-email-vs-social-media-marketing',
'https://blog.becgrowth.com/blog/cold-email-vs-email-marketing-b2b',
'https://blog.becgrowth.com/blog/cold-email-vs-influencer-marketing-b2b',
'https://blog.becgrowth.com/blog/cold-email-vs-account-based-marketing',
'https://blog.becgrowth.com/blog/cold-email-vs-demand-generation',
'https://blog.becgrowth.com/blog/cold-email-vs-product-led-growth',
'https://blog.becgrowth.com/blog/cold-email-vs-sales-led-growth',
'https://blog.becgrowth.com/blog/cold-email-vs-community-led-growth',
'https://blog.becgrowth.com/blog/cold-email-for-b2b-revenue-operations',
'https://blog.becgrowth.com/blog/cold-email-for-b2b-sales-operations',
'https://blog.becgrowth.com/blog/cold-email-for-b2b-marketing-operations',
'https://blog.becgrowth.com/blog/cold-email-for-b2b-customer-operations',
'https://blog.becgrowth.com/blog/cold-email-for-b2b-people-operations',
'https://blog.becgrowth.com/blog/cold-email-for-b2b-finance-operations',
'https://blog.becgrowth.com/blog/cold-email-for-b2b-legal-operations',
'https://blog.becgrowth.com/blog/cold-email-for-b2b-it-operations',
'https://blog.becgrowth.com/blog/cold-email-for-b2b-data-operations',
'https://blog.becgrowth.com/blog/cold-email-for-b2b-product-operations',
'https://blog.becgrowth.com/blog/cold-email-case-study-agency-2026',
'https://blog.becgrowth.com/blog/cold-email-case-study-saas-2026',
'https://blog.becgrowth.com/blog/cold-email-case-study-consultant-2026',
'https://blog.becgrowth.com/blog/cold-email-case-study-startup-2026',
'https://blog.becgrowth.com/blog/cold-email-case-study-fintech-2026',
'https://blog.becgrowth.com/blog/cold-email-case-study-healthtech-2026',
'https://blog.becgrowth.com/blog/cold-email-case-study-ecommerce-2026',
'https://blog.becgrowth.com/blog/cold-email-case-study-real-estate-2026',
'https://blog.becgrowth.com/blog/cold-email-case-study-coaching-2026',
'https://blog.becgrowth.com/blog/cold-email-case-study-marketing-agency',
'https://blog.becgrowth.com/blog/cold-email-results-agency-2026',
'https://blog.becgrowth.com/blog/cold-email-results-saas-2026',
'https://blog.becgrowth.com/blog/cold-email-results-consultant-2026',
'https://blog.becgrowth.com/blog/cold-email-results-startup-2026',
'https://blog.becgrowth.com/blog/cold-email-results-b2b-2026',
'https://blog.becgrowth.com/blog/cold-email-success-story-agency',
'https://blog.becgrowth.com/blog/cold-email-success-story-saas',
'https://blog.becgrowth.com/blog/cold-email-success-story-consultant',
'https://blog.becgrowth.com/blog/cold-email-success-story-startup',
'https://blog.becgrowth.com/blog/cold-email-success-story-founder',
'https://blog.becgrowth.com/blog/cold-email-roi-story-agency-2026',
'https://blog.becgrowth.com/blog/cold-email-roi-story-saas-2026',
'https://blog.becgrowth.com/blog/cold-email-roi-story-consultant',
'https://blog.becgrowth.com/blog/cold-email-roi-story-startup-2026',
'https://blog.becgrowth.com/blog/cold-email-roi-story-founder-2026',
'https://blog.becgrowth.com/blog/cold-email-30-day-results-guide',
'https://blog.becgrowth.com/blog/cold-email-60-day-results-guide',
'https://blog.becgrowth.com/blog/cold-email-90-day-results-guide',
'https://blog.becgrowth.com/blog/cold-email-6-month-results-guide',
'https://blog.becgrowth.com/blog/cold-email-12-month-results-guide',
'https://blog.becgrowth.com/blog/cold-email-week-1-results-guide',
'https://blog.becgrowth.com/blog/cold-email-week-2-results-guide',
'https://blog.becgrowth.com/blog/cold-email-week-3-results-guide',
'https://blog.becgrowth.com/blog/cold-email-week-4-results-guide',
'https://blog.becgrowth.com/blog/cold-email-first-week-guide',
'https://blog.becgrowth.com/blog/cold-email-first-month-guide',
'https://blog.becgrowth.com/blog/cold-email-first-quarter-guide',
'https://blog.becgrowth.com/blog/cold-email-first-year-guide',
'https://blog.becgrowth.com/blog/cold-email-timeline-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-roadmap-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-blueprint-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-framework-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-system-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-process-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-workflow-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-playbook-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-strategy-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-masterclass-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-crash-course-2026',
'https://blog.becgrowth.com/blog/cold-email-bootcamp-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-accelerator-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-intensive-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-workshop-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-course-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-training-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-mentorship-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-coaching-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-consulting-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-for-b2b-media-outreach',
'https://blog.becgrowth.com/blog/cold-email-for-b2b-pr-outreach',
'https://blog.becgrowth.com/blog/cold-email-for-b2b-influencer-outreach',
'https://blog.becgrowth.com/blog/cold-email-for-b2b-podcast-outreach',
'https://blog.becgrowth.com/blog/cold-email-for-b2b-speaker-outreach',
'https://blog.becgrowth.com/blog/cold-email-for-b2b-event-outreach',
'https://blog.becgrowth.com/blog/cold-email-for-b2b-conference-outreach',
'https://blog.becgrowth.com/blog/cold-email-for-b2b-webinar-outreach',
'https://blog.becgrowth.com/blog/cold-email-for-b2b-press-outreach',
'https://blog.becgrowth.com/blog/cold-email-for-b2b-journalist-outreach',
'https://blog.becgrowth.com/blog/cold-email-for-b2b-analyst-outreach',
'https://blog.becgrowth.com/blog/cold-email-for-b2b-blogger-outreach',
'https://blog.becgrowth.com/blog/cold-email-for-b2b-newsletter-outreach',
'https://blog.becgrowth.com/blog/cold-email-for-b2b-community-outreach',
'https://blog.becgrowth.com/blog/cold-email-for-b2b-association-outreach',
'https://blog.becgrowth.com/blog/cold-email-productivity-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-efficiency-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-optimization-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-improvement-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-enhancement-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-acceleration-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-amplification-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-maximization-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-multiplication-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-compounding-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-for-b2b-digital-transformation',
'https://blog.becgrowth.com/blog/cold-email-for-b2b-digital-marketing',
'https://blog.becgrowth.com/blog/cold-email-for-b2b-digital-sales',
'https://blog.becgrowth.com/blog/cold-email-for-b2b-digital-growth',
'https://blog.becgrowth.com/blog/cold-email-for-b2b-digital-strategy',
'https://blog.becgrowth.com/blog/cold-email-for-b2b-digital-outreach',
'https://blog.becgrowth.com/blog/cold-email-for-b2b-digital-prospecting',
'https://blog.becgrowth.com/blog/cold-email-for-b2b-digital-acquisition',
'https://blog.becgrowth.com/blog/cold-email-for-b2b-digital-pipeline',
'https://blog.becgrowth.com/blog/cold-email-for-b2b-digital-revenue',
'https://blog.becgrowth.com/blog/cold-email-mindset-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-psychology-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-persuasion-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-influence-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-trust-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-credibility-guide-b2b',
'https://blog.becgrowth.com/blog/cold-email-authority-guide-b2b',
'https://blog.becgrowth.com/blog/cold-email-reciprocity-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-scarcity-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-urgency-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-curiosity-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-empathy-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-storytelling-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-humor-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-directness-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-brevity-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-clarity-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-specificity-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-relevance-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-timing-psychology-guide',
'https://blog.becgrowth.com/blog/cold-email-buyer-psychology-guide',
'https://blog.becgrowth.com/blog/cold-email-decision-maker-psychology',
'https://blog.becgrowth.com/blog/cold-email-gatekeeper-psychology',
'https://blog.becgrowth.com/blog/cold-email-prospect-psychology-2026',
'https://blog.becgrowth.com/blog/cold-email-for-b2b-north-america',
'https://blog.becgrowth.com/blog/cold-email-for-b2b-south-america',
'https://blog.becgrowth.com/blog/cold-email-for-b2b-western-europe',
'https://blog.becgrowth.com/blog/cold-email-for-b2b-eastern-europe',
'https://blog.becgrowth.com/blog/cold-email-for-b2b-middle-east',
'https://blog.becgrowth.com/blog/cold-email-for-b2b-southeast-asia',
'https://blog.becgrowth.com/blog/cold-email-for-b2b-south-asia',
'https://blog.becgrowth.com/blog/cold-email-for-b2b-east-asia',
'https://blog.becgrowth.com/blog/cold-email-for-b2b-sub-saharan-africa',
'https://blog.becgrowth.com/blog/cold-email-for-b2b-north-africa',
'https://blog.becgrowth.com/blog/cold-email-compliance-gdpr-2026',
'https://blog.becgrowth.com/blog/cold-email-compliance-can-spam-2026',
'https://blog.becgrowth.com/blog/cold-email-compliance-casl-2026',
'https://blog.becgrowth.com/blog/cold-email-compliance-uk-gdpr-2026',
'https://blog.becgrowth.com/blog/cold-email-compliance-ccpa-2026',
'https://blog.becgrowth.com/blog/cold-email-legal-guide-usa-2026',
'https://blog.becgrowth.com/blog/cold-email-legal-guide-uk-2026',
'https://blog.becgrowth.com/blog/cold-email-legal-guide-canada-2026',
'https://blog.becgrowth.com/blog/cold-email-legal-guide-australia-2026',
'https://blog.becgrowth.com/blog/cold-email-legal-guide-europe-2026',
'https://blog.becgrowth.com/blog/cold-email-opt-out-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-unsubscribe-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-consent-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-data-privacy-guide-2026',
'https://blog.becgrowth.com/blog/cold-email-data-protection-guide',
'https://blog.becgrowth.com/blog/cold-email-for-b2b-manufacturing-usa',
'https://blog.becgrowth.com/blog/cold-email-for-b2b-construction-usa',
'https://blog.becgrowth.com/blog/cold-email-for-b2b-healthcare-usa',
'https://blog.becgrowth.com/blog/cold-email-for-b2b-finance-usa',
'https://blog.becgrowth.com/blog/cold-email-for-b2b-technology-usa',
'https://blog.becgrowth.com/blog/cold-email-for-b2b-retail-usa',
'https://blog.becgrowth.com/blog/cold-email-for-b2b-logistics-usa',
'https://blog.becgrowth.com/blog/cold-email-for-b2b-real-estate-usa',
'https://blog.becgrowth.com/blog/cold-email-for-b2b-education-usa',
'https://blog.becgrowth.com/blog/cold-email-for-b2b-hospitality-usa',
'https://blog.becgrowth.com/blog/cold-email-for-b2b-manufacturing-uk',
'https://blog.becgrowth.com/blog/cold-email-for-b2b-construction-uk',
'https://blog.becgrowth.com/blog/cold-email-for-b2b-healthcare-uk',
'https://blog.becgrowth.com/blog/cold-email-for-b2b-finance-uk',
'https://blog.becgrowth.com/blog/cold-email-for-b2b-technology-uk',
'https://blog.becgrowth.com/blog/cold-email-for-b2b-manufacturing-dubai',
'https://blog.becgrowth.com/blog/cold-email-for-b2b-construction-dubai',
'https://blog.becgrowth.com/blog/cold-email-for-b2b-healthcare-dubai',
'https://blog.becgrowth.com/blog/cold-email-for-b2b-finance-dubai',
'https://blog.becgrowth.com/blog/cold-email-for-b2b-technology-dubai',
'https://blog.becgrowth.com/blog/cold-email-for-b2b-real-estate-dubai',
'https://blog.becgrowth.com/blog/cold-email-for-b2b-retail-dubai',
'https://blog.becgrowth.com/blog/cold-email-for-b2b-logistics-dubai',
'https://blog.becgrowth.com/blog/cold-email-for-b2b-hospitality-dubai',
'https://blog.becgrowth.com/blog/cold-email-for-b2b-education-dubai',
'https://blog.becgrowth.com/blog/cold-email-saas-onboarding-guide',
'https://blog.becgrowth.com/blog/cold-email-saas-activation-guide',
'https://blog.becgrowth.com/blog/cold-email-saas-retention-guide',
'https://blog.becgrowth.com/blog/cold-email-saas-expansion-guide',
'https://blog.becgrowth.com/blog/cold-email-saas-churn-reduction',
'https://blog.becgrowth.com/blog/cold-email-saas-upsell-guide',
'https://blog.becgrowth.com/blog/cold-email-saas-cross-sell-guide',
'https://blog.becgrowth.com/blog/cold-email-saas-renewal-guide',
'https://blog.becgrowth.com/blog/cold-email-saas-win-back-guide',
'https://blog.becgrowth.com/blog/cold-email-saas-reactivation-guide',
'https://blog.becgrowth.com/blog/cold-email-agency-onboarding-clients',
'https://blog.becgrowth.com/blog/cold-email-agency-retaining-clients',
'https://blog.becgrowth.com/blog/cold-email-agency-upselling-clients',
'https://blog.becgrowth.com/blog/cold-email-agency-reporting-clients',
'https://blog.becgrowth.com/blog/cold-email-agency-managing-clients',
'https://blog.becgrowth.com/blog/cold-email-agency-scaling-clients',
'https://blog.becgrowth.com/blog/cold-email-agency-winning-clients',
'https://blog.becgrowth.com/blog/cold-email-agency-keeping-clients',
'https://blog.becgrowth.com/blog/cold-email-agency-delighting-clients',
'https://blog.becgrowth.com/blog/cold-email-agency-surprising-clients',
'https://blog.becgrowth.com/blog/cold-email-agency-growing-clients',
];

async function submitUrls() {
  let success = 0, failed = 0;
  console.log(`\nSubmitting ${urls.length} URLs...\n`);
  for (let i = 0; i < urls.length; i++) {
    const url = urls[i];
    try {
      await indexing.urlNotifications.publish({
        requestBody: { url, type: 'URL_UPDATED' },
      });
      success++;
      console.log(`✓ [${i+1}/${urls.length}] ${url}`);
    } catch (err) {
      failed++;
      console.log(`✕ [${i+1}/${urls.length}] ${url} - ${err.response?.data?.error?.message || err.message}`);
    }
    await new Promise(r => setTimeout(r, 300));
  }
  console.log(`\nDone! Success: ${success}, Failed: ${failed}`);
}

submitUrls().catch(console.error);