const { google } = require('googleapis');
const fs = require('fs');

const creds = JSON.parse(fs.readFileSync('./oauth-credentials.json'));
const { client_id, client_secret } = creds.installed;
const tokens = JSON.parse(fs.readFileSync('./oauth-token.json'));

const oauth2Client = new google.auth.OAuth2(client_id, client_secret, 'http://localhost:3000');
oauth2Client.setCredentials(tokens);

const indexing = google.indexing({ version: 'v3', auth: oauth2Client });

const urls = [
  'https://blog.becgrowth.com/sitemap.xml',
  'https://blog.becgrowth.com/blog/cold-email-strategy-b2b-agencies-2026',
  'https://blog.becgrowth.com/blog/how-to-write-cold-emails-that-get-replies',
  'https://blog.becgrowth.com/blog/cold-email-deliverability-complete-guide',
  'https://blog.becgrowth.com/blog/how-to-book-20-meetings-a-month-cold-email',
  'https://blog.becgrowth.com/blog/cold-email-vs-linkedin-outreach-2026',
  'https://blog.becgrowth.com/blog/b2b-cold-email-lead-generation-guide',
  'https://blog.becgrowth.com/blog/cold-email-subject-lines-that-get-opened',
  'https://blog.becgrowth.com/blog/how-to-warm-up-email-domain',
  'https://blog.becgrowth.com/blog/cold-email-follow-up-sequence-guide',
  'https://blog.becgrowth.com/blog/b2b-appointment-setting-complete-guide',
  'https://blog.becgrowth.com/blog/how-to-build-cold-email-list-from-scratch',
  'https://blog.becgrowth.com/blog/cold-email-personalization-at-scale',
  'https://blog.becgrowth.com/blog/cold-email-vs-paid-ads-b2b-comparison',
  'https://blog.becgrowth.com/blog/how-to-close-high-ticket-clients-cold-email',
  'https://blog.becgrowth.com/blog/cold-email-infrastructure-setup-guide',
  'https://blog.becgrowth.com/blog/spf-dkim-dmarc-setup-cold-email',
  'https://blog.becgrowth.com/blog/how-to-scale-b2b-agency-cold-email',
  'https://blog.becgrowth.com/blog/cold-email-templates-b2b-agencies',
  'https://blog.becgrowth.com/blog/how-to-get-first-clients-agency-no-experience',
  'https://blog.becgrowth.com/blog/b2b-lead-generation-without-paid-ads',
  'https://blog.becgrowth.com/blog/cold-email-open-rates-benchmarks-2026',
  'https://blog.becgrowth.com/blog/how-to-hire-sdr-vs-cold-email-agency',
  'https://blog.becgrowth.com/blog/cold-email-copywriting-complete-guide',
  'https://blog.becgrowth.com/blog/how-to-find-decision-makers-cold-email',
  'https://blog.becgrowth.com/blog/b2b-outbound-sales-system-guide',
  'https://blog.becgrowth.com/blog/cold-email-reply-rate-optimization',
  'https://blog.becgrowth.com/blog/how-to-book-sales-calls-cold-email',
  'https://blog.becgrowth.com/blog/agency-client-acquisition-system-2026',
  'https://blog.becgrowth.com/blog/cold-email-for-saas-companies-guide',
  'https://blog.becgrowth.com/blog/how-to-write-cold-email-opener',
  'https://blog.becgrowth.com/blog/cold-email-for-coaches-and-consultants',
  'https://blog.becgrowth.com/blog/b2b-sales-pipeline-cold-email-guide',
  'https://blog.becgrowth.com/blog/how-to-avoid-spam-folder-cold-email',
  'https://blog.becgrowth.com/blog/cold-email-sequence-templates-2026',
  'https://blog.becgrowth.com/blog/how-to-target-icp-cold-email',
  'https://blog.becgrowth.com/blog/cold-email-for-marketing-agencies',
  'https://blog.becgrowth.com/blog/b2b-outreach-automation-tools-2026',
  'https://blog.becgrowth.com/blog/how-to-measure-cold-email-roi',
  'https://blog.becgrowth.com/blog/cold-email-mistakes-to-avoid-2026',
  'https://blog.becgrowth.com/blog/how-to-scale-cold-email-campaigns',
  'https://blog.becgrowth.com/blog/b2b-client-acquisition-cost-reduction',
  'https://blog.becgrowth.com/blog/cold-email-for-recruitment-agencies',
  'https://blog.becgrowth.com/blog/how-to-write-cold-email-cta',
  'https://blog.becgrowth.com/blog/cold-email-list-building-apollo-guide',
  'https://blog.becgrowth.com/blog/b2b-sales-email-best-practices-2026',
  'https://blog.becgrowth.com/blog/how-to-get-20-percent-reply-rate-cold-email',
  'https://blog.becgrowth.com/blog/cold-email-for-web-design-agencies',
  'https://blog.becgrowth.com/blog/b2b-outbound-vs-inbound-marketing',
  'https://blog.becgrowth.com/blog/how-to-build-b2b-sales-team',
  'https://blog.becgrowth.com/blog/cold-email-for-it-companies',
  'https://blog.becgrowth.com/blog/instantly-vs-lemlist-vs-smartlead-2026',
  'https://blog.becgrowth.com/blog/apollo-vs-clay-lead-generation',
  'https://blog.becgrowth.com/blog/cold-email-for-pr-agencies',
  'https://blog.becgrowth.com/blog/how-to-add-30k-revenue-cold-email',
  'https://blog.becgrowth.com/blog/cold-email-for-video-production-companies',
  'https://blog.becgrowth.com/blog/b2b-cold-email-case-study-14000-in-45-days',
  'https://blog.becgrowth.com/blog/how-to-go-from-7k-to-35k-month-agency',
  'https://blog.becgrowth.com/blog/cold-email-for-ecommerce-brands',
  'https://blog.becgrowth.com/blog/b2b-email-outreach-best-practices',
  'https://blog.becgrowth.com/blog/how-to-write-b2b-cold-email-2026',
  'https://blog.becgrowth.com/blog/cold-email-for-financial-services',
  'https://blog.becgrowth.com/blog/how-to-generate-b2b-leads-cold-email',
  'https://blog.becgrowth.com/blog/cold-email-agency-vs-in-house-sdr',
  'https://blog.becgrowth.com/blog/how-to-build-outbound-system-agency',
  'https://blog.becgrowth.com/blog/cold-email-for-real-estate-companies',
  'https://blog.becgrowth.com/blog/b2b-prospecting-tools-2026',
  'https://blog.becgrowth.com/blog/cold-email-sender-reputation-guide',
  'https://blog.becgrowth.com/blog/how-to-write-cold-email-ps-line',
  'https://blog.becgrowth.com/blog/cold-email-for-logistics-companies',
  'https://blog.becgrowth.com/blog/how-to-run-cold-email-campaign-2026',
  'https://blog.becgrowth.com/blog/b2b-cold-outreach-complete-playbook',
  'https://blog.becgrowth.com/blog/cold-email-for-consulting-firms',
  'https://blog.becgrowth.com/blog/how-to-get-replies-cold-email-2026',
  'https://blog.becgrowth.com/blog/cold-email-frequency-how-many-to-send',
  'https://blog.becgrowth.com/blog/b2b-sales-outreach-metrics-guide',
  'https://blog.becgrowth.com/blog/cold-email-for-staffing-agencies',
  'https://blog.becgrowth.com/blog/how-to-use-clay-for-cold-email',
  'https://blog.becgrowth.com/blog/cold-email-inbox-placement-guide',
  'https://blog.becgrowth.com/blog/b2b-pipeline-generation-cold-email',
  'https://blog.becgrowth.com/blog/cold-email-for-accounting-firms',
  'https://blog.becgrowth.com/blog/how-to-use-instantly-cold-email',
  'https://blog.becgrowth.com/blog/cold-email-bounce-rate-guide',
  'https://blog.becgrowth.com/blog/b2b-cold-email-for-startups',
  'https://blog.becgrowth.com/blog/how-to-write-cold-email-subject-line',
  'https://blog.becgrowth.com/blog/cold-email-for-health-companies',
  'https://blog.becgrowth.com/blog/how-to-find-email-addresses-b2b',
  'https://blog.becgrowth.com/blog/cold-email-sending-limits-guide',
  'https://blog.becgrowth.com/blog/b2b-sales-cadence-cold-email',
  'https://blog.becgrowth.com/blog/cold-email-for-law-firms',
  'https://blog.becgrowth.com/blog/how-to-use-linkedin-sales-navigator-cold-email',
  'https://blog.becgrowth.com/blog/cold-email-unsubscribe-rate-guide',
  'https://blog.becgrowth.com/blog/b2b-outbound-email-compliance-guide',
  'https://blog.becgrowth.com/blog/cold-email-for-construction-companies',
  'https://blog.becgrowth.com/blog/how-to-write-b2b-email-value-proposition',
  'https://blog.becgrowth.com/blog/cold-email-testing-ab-guide',
  'https://blog.becgrowth.com/blog/b2b-lead-qualification-cold-email',
  'https://blog.becgrowth.com/blog/cold-email-for-insurance-companies',
  'https://blog.becgrowth.com/blog/how-to-track-cold-email-campaigns',
  'https://blog.becgrowth.com/blog/cold-email-reply-handling-guide',
  'https://blog.becgrowth.com/blog/b2b-meeting-booking-cold-email',
  'https://blog.becgrowth.com/blog/cold-email-for-manufacturing-companies',
  'https://blog.becgrowth.com/blog/how-to-use-apollo-for-cold-email',
  'https://blog.becgrowth.com/blog/cold-email-domain-setup-guide',
  'https://blog.becgrowth.com/blog/b2b-email-marketing-vs-cold-email',
  'https://blog.becgrowth.com/blog/cold-email-for-technology-companies',
  'https://blog.becgrowth.com/blog/how-to-write-cold-email-pain-points',
  'https://blog.becgrowth.com/blog/cold-email-for-healthcare-companies',
  'https://blog.becgrowth.com/blog/b2b-sales-email-sequence-guide',
  'https://blog.becgrowth.com/blog/cold-email-list-cleaning-guide',
  'https://blog.becgrowth.com/blog/how-to-get-clients-cold-email-agency',
  'https://blog.becgrowth.com/blog/cold-email-for-event-companies',
  'https://blog.becgrowth.com/blog/b2b-cold-email-personalization-guide',
  'https://blog.becgrowth.com/blog/cold-email-for-media-companies',
  'https://blog.becgrowth.com/blog/how-to-write-cold-email-social-proof',
  'https://blog.becgrowth.com/blog/cold-email-outreach-checklist-2026',
  'https://blog.becgrowth.com/blog/b2b-sales-prospecting-guide-2026',
  'https://blog.becgrowth.com/blog/cold-email-for-education-companies',
  'https://blog.becgrowth.com/blog/how-to-write-cold-email-without-experience',
  'https://blog.becgrowth.com/blog/cold-email-deliverability-checklist',
  'https://blog.becgrowth.com/blog/b2b-outbound-lead-generation-2026',
  'https://blog.becgrowth.com/blog/cold-email-for-hospitality-companies',
  'https://blog.becgrowth.com/blog/how-to-use-smartlead-cold-email',
  'https://blog.becgrowth.com/blog/cold-email-sending-schedule-guide',
  'https://blog.becgrowth.com/blog/b2b-revenue-growth-cold-email',
  'https://blog.becgrowth.com/blog/cold-email-for-retail-companies',
  'https://blog.becgrowth.com/blog/how-to-write-cold-email-without-case-studies',
  'https://blog.becgrowth.com/blog/cold-email-for-automotive-companies',
  'https://blog.becgrowth.com/blog/b2b-cold-email-metrics-to-track',
  'https://blog.becgrowth.com/blog/cold-email-for-nonprofit-organizations',
  'https://blog.becgrowth.com/blog/how-to-build-cold-email-agency-2026',
  'https://blog.becgrowth.com/blog/cold-email-for-architecture-firms',
  'https://blog.becgrowth.com/blog/b2b-sales-development-rep-guide',
  'https://blog.becgrowth.com/blog/cold-email-for-pharmaceutical-companies',
  'https://blog.becgrowth.com/blog/how-to-write-cold-email-first-line',
  'https://blog.becgrowth.com/blog/cold-email-benchmark-report-2026',
  'https://blog.becgrowth.com/blog/b2b-email-outreach-tools-comparison',
  'https://blog.becgrowth.com/blog/cold-email-for-food-beverage-companies',
  'https://blog.becgrowth.com/blog/how-to-run-outbound-campaign-b2b',
  'https://blog.becgrowth.com/blog/cold-email-for-sports-companies',
  'https://blog.becgrowth.com/blog/b2b-sales-funnel-cold-email-guide',
  'https://blog.becgrowth.com/blog/cold-email-for-fashion-companies',
  'https://blog.becgrowth.com/blog/how-to-write-cold-email-with-ai',
  'https://blog.becgrowth.com/blog/cold-email-for-travel-companies',
  'https://blog.becgrowth.com/blog/b2b-cold-email-gdpr-compliance',
  'https://blog.becgrowth.com/blog/cold-email-for-energy-companies',
  'https://blog.becgrowth.com/blog/how-to-use-lemlist-cold-email',
  'https://blog.becgrowth.com/blog/cold-email-for-media-buying-agencies',
  'https://blog.becgrowth.com/blog/b2b-cold-email-can-spam-compliance',
  'https://blog.becgrowth.com/blog/cold-email-for-biotech-companies',
  'https://blog.becgrowth.com/blog/how-to-get-100-replies-cold-email',
  'https://blog.becgrowth.com/blog/cold-email-for-cybersecurity-companies',
  'https://blog.becgrowth.com/blog/b2b-account-based-marketing-cold-email',
  'https://blog.becgrowth.com/blog/cold-email-for-fintech-companies',
  'https://blog.becgrowth.com/blog/how-to-set-up-email-sending-infrastructure',
  'https://blog.becgrowth.com/blog/cold-email-for-proptech-companies',
  'https://blog.becgrowth.com/blog/b2b-sales-outreach-playbook-2026',
  'https://blog.becgrowth.com/blog/cold-email-for-cleantech-companies',
  'https://blog.becgrowth.com/blog/how-to-close-deals-cold-email-2026',
  'https://blog.becgrowth.com/blog/cold-email-for-edtech-companies',
  'https://blog.becgrowth.com/blog/b2b-cold-email-roi-calculator-guide',
  'https://blog.becgrowth.com/blog/cold-email-for-legaltech-companies',
  'https://blog.becgrowth.com/blog/how-to-write-cold-email-for-agencies',
  'https://blog.becgrowth.com/blog/cold-email-for-hr-tech-companies',
  'https://blog.becgrowth.com/blog/b2b-cold-email-statistics-2026',
  'https://blog.becgrowth.com/blog/cold-email-for-martech-companies',
  'https://blog.becgrowth.com/blog/how-to-use-hunter-io-cold-email',
  'https://blog.becgrowth.com/blog/cold-email-for-adtech-companies',
  'https://blog.becgrowth.com/blog/b2b-outbound-sales-statistics-2026',
  'https://blog.becgrowth.com/blog/cold-email-for-insurtech-companies',
  'https://blog.becgrowth.com/blog/how-to-qualify-leads-cold-email',
  'https://blog.becgrowth.com/blog/cold-email-for-supply-chain-companies',
  'https://blog.becgrowth.com/blog/b2b-cold-email-frequency-guide',
  'https://blog.becgrowth.com/blog/cold-email-for-logistics-tech-companies',
  'https://blog.becgrowth.com/blog/how-to-handle-cold-email-objections',
  'https://blog.becgrowth.com/blog/cold-email-for-data-analytics-companies',
  'https://blog.becgrowth.com/blog/b2b-cold-email-glossary-2026',
  'https://blog.becgrowth.com/blog/cold-email-for-cloud-computing-companies',
  'https://blog.becgrowth.com/blog/how-to-write-cold-email-breakup-message',
  'https://blog.becgrowth.com/blog/cold-email-for-ai-companies',
  'https://blog.becgrowth.com/blog/b2b-cold-email-faq-2026',
  'https://blog.becgrowth.com/blog/cold-email-for-blockchain-companies',
  'https://blog.becgrowth.com/blog/how-to-use-zoominfo-cold-email',
  'https://blog.becgrowth.com/blog/cold-email-for-gaming-companies',
  'https://blog.becgrowth.com/blog/b2b-cold-email-industry-report-2026',
  'https://blog.becgrowth.com/blog/cold-email-for-media-production-companies',
  'https://blog.becgrowth.com/blog/how-to-automate-cold-email-outreach',
  'https://blog.becgrowth.com/blog/cold-email-for-creative-agencies',
  'https://blog.becgrowth.com/blog/b2b-cold-email-templates-2026',
  'https://blog.becgrowth.com/blog/cold-email-for-growth-agencies',
  'https://blog.becgrowth.com/blog/how-to-do-cold-email-outreach-2026',
  'https://blog.becgrowth.com/blog/cold-email-for-performance-marketing-agencies',
  'https://blog.becgrowth.com/blog/b2b-cold-email-best-practices-2026',
  'https://blog.becgrowth.com/blog/cold-email-for-seo-agencies',
  'https://blog.becgrowth.com/blog/how-to-get-meetings-cold-email-2026',
  'https://blog.becgrowth.com/blog/cold-email-for-ppc-agencies',
  'https://blog.becgrowth.com/blog/b2b-cold-email-conversion-rate-guide',
  'https://blog.becgrowth.com/blog/cold-email-for-social-media-agencies',
  'https://blog.becgrowth.com/blog/how-to-write-cold-email-that-converts',
  'https://blog.becgrowth.com/blog/cold-email-for-content-marketing-agencies',
  'https://blog.becgrowth.com/blog/b2b-cold-email-complete-guide-2026',
];

async function submitUrls() {
  let success = 0, failed = 0;
  console.log(`\nSubmitting ${urls.length} URLs...\n`);
  for (let i = 0; i < urls.length; i++) {
    const url = urls[i];
    try {
      await indexing.urlNotifications.publish({
        requestBody: { url, type: 'URL_UPDATED' },
      });
      success++;
      console.log(`✓ [${i+1}/${urls.length}] ${url}`);
    } catch (err) {
      failed++;
      console.log(`✕ [${i+1}/${urls.length}] ${url} - ${err.response?.data?.error?.message || err.message}`);
    }
    await new Promise(r => setTimeout(r, 300));
  }
  console.log(`\nDone! Success: ${success}, Failed: ${failed}`);
}

submitUrls().catch(console.error);