import type { MetadataRoute } from 'next';

const staticPages: MetadataRoute.Sitemap = [
  { url: 'https://blog.becgrowth.com', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog', lastModified: new Date() },
];

const blogPosts1: MetadataRoute.Sitemap = [
  { url: 'https://blog.becgrowth.com/blog/cold-email-strategy-b2b-agencies-2026', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/how-to-write-cold-emails-that-get-replies', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-deliverability-complete-guide', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/how-to-book-20-meetings-a-month-cold-email', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-vs-linkedin-outreach-2026', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/b2b-cold-email-lead-generation-guide', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-subject-lines-that-get-opened', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/how-to-warm-up-email-domain', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-follow-up-sequence-guide', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/b2b-appointment-setting-complete-guide', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/how-to-build-cold-email-list-from-scratch', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-personalization-at-scale', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-vs-paid-ads-b2b-comparison', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/how-to-close-high-ticket-clients-cold-email', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-infrastructure-setup-guide', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/spf-dkim-dmarc-setup-cold-email', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/how-to-scale-b2b-agency-cold-email', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-templates-b2b-agencies', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/how-to-get-first-clients-agency-no-experience', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/b2b-lead-generation-without-paid-ads', lastModified: new Date() },
];

const blogPosts2: MetadataRoute.Sitemap = [
  { url: 'https://blog.becgrowth.com/blog/cold-email-open-rates-benchmarks-2026', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/how-to-hire-sdr-vs-cold-email-agency', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-copywriting-complete-guide', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/how-to-find-decision-makers-cold-email', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/b2b-outbound-sales-system-guide', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-reply-rate-optimization', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/how-to-book-sales-calls-cold-email', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/agency-client-acquisition-system-2026', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-for-saas-companies-guide', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/how-to-write-cold-email-opener', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-for-coaches-and-consultants', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/b2b-sales-pipeline-cold-email-guide', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/how-to-avoid-spam-folder-cold-email', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-sequence-templates-2026', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/how-to-target-icp-cold-email', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-for-marketing-agencies', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/b2b-outreach-automation-tools-2026', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/how-to-measure-cold-email-roi', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-mistakes-to-avoid-2026', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/how-to-scale-cold-email-campaigns', lastModified: new Date() },
];

const blogPosts3: MetadataRoute.Sitemap = [
  { url: 'https://blog.becgrowth.com/blog/b2b-client-acquisition-cost-reduction', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-for-recruitment-agencies', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/how-to-write-cold-email-cta', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-list-building-apollo-guide', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/b2b-sales-email-best-practices-2026', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/how-to-get-20-percent-reply-rate-cold-email', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-for-web-design-agencies', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/b2b-outbound-vs-inbound-marketing', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/how-to-build-b2b-sales-team', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-for-it-companies', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/instantly-vs-lemlist-vs-smartlead-2026', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/apollo-vs-clay-lead-generation', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-for-pr-agencies', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/how-to-add-30k-revenue-cold-email', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-for-video-production-companies', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/b2b-cold-email-case-study-14000-in-45-days', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/how-to-go-from-7k-to-35k-month-agency', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-for-ecommerce-brands', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/b2b-email-outreach-best-practices', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/how-to-write-b2b-cold-email-2026', lastModified: new Date() },
];

const blogPosts4: MetadataRoute.Sitemap = [
  { url: 'https://blog.becgrowth.com/blog/cold-email-for-financial-services', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/how-to-generate-b2b-leads-cold-email', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-agency-vs-in-house-sdr', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/how-to-build-outbound-system-agency', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-for-real-estate-companies', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/b2b-prospecting-tools-2026', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-sender-reputation-guide', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/how-to-write-cold-email-ps-line', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-for-logistics-companies', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/how-to-run-cold-email-campaign-2026', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/b2b-cold-outreach-complete-playbook', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-for-consulting-firms', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/how-to-get-replies-cold-email-2026', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-frequency-how-many-to-send', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/b2b-sales-outreach-metrics-guide', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-for-staffing-agencies', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/how-to-use-clay-for-cold-email', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-inbox-placement-guide', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/b2b-pipeline-generation-cold-email', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-for-accounting-firms', lastModified: new Date() },
];

const blogPosts5: MetadataRoute.Sitemap = [
  { url: 'https://blog.becgrowth.com/blog/how-to-use-instantly-cold-email', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-bounce-rate-guide', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/b2b-cold-email-for-startups', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/how-to-write-cold-email-subject-line', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-for-health-companies', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/how-to-find-email-addresses-b2b', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-sending-limits-guide', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/b2b-sales-cadence-cold-email', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-for-law-firms', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/how-to-use-linkedin-sales-navigator-cold-email', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-unsubscribe-rate-guide', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/b2b-outbound-email-compliance-guide', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-for-construction-companies', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/how-to-write-b2b-email-value-proposition', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-testing-ab-guide', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/b2b-lead-qualification-cold-email', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-for-insurance-companies', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/how-to-track-cold-email-campaigns', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-reply-handling-guide', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/b2b-meeting-booking-cold-email', lastModified: new Date() },
];

const blogPosts6: MetadataRoute.Sitemap = [
  { url: 'https://blog.becgrowth.com/blog/cold-email-for-manufacturing-companies', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/how-to-use-apollo-for-cold-email', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-domain-setup-guide', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/b2b-email-marketing-vs-cold-email', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-for-technology-companies', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/how-to-write-cold-email-pain-points', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-for-healthcare-companies', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/b2b-sales-email-sequence-guide', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-list-cleaning-guide', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/how-to-get-clients-cold-email-agency', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-for-event-companies', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/b2b-cold-email-personalization-guide', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-for-media-companies', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/how-to-write-cold-email-social-proof', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-outreach-checklist-2026', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/b2b-sales-prospecting-guide-2026', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-for-education-companies', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/how-to-write-cold-email-without-experience', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-deliverability-checklist', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/b2b-outbound-lead-generation-2026', lastModified: new Date() },
];

const blogPosts7: MetadataRoute.Sitemap = [
  { url: 'https://blog.becgrowth.com/blog/cold-email-for-hospitality-companies', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/how-to-use-smartlead-cold-email', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-sending-schedule-guide', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/b2b-revenue-growth-cold-email', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-for-retail-companies', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/how-to-write-cold-email-without-case-studies', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-for-automotive-companies', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/b2b-cold-email-metrics-to-track', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-for-nonprofit-organizations', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/how-to-build-cold-email-agency-2026', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-for-architecture-firms', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/b2b-sales-development-rep-guide', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-for-pharmaceutical-companies', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/how-to-write-cold-email-first-line', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-benchmark-report-2026', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/b2b-email-outreach-tools-comparison', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-for-food-beverage-companies', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/how-to-run-outbound-campaign-b2b', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-for-sports-companies', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/b2b-sales-funnel-cold-email-guide', lastModified: new Date() },
];

const blogPosts8: MetadataRoute.Sitemap = [
  { url: 'https://blog.becgrowth.com/blog/cold-email-for-fashion-companies', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/how-to-write-cold-email-with-ai', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-for-travel-companies', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/b2b-cold-email-gdpr-compliance', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-for-energy-companies', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/how-to-use-lemlist-cold-email', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-for-media-buying-agencies', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/b2b-cold-email-can-spam-compliance', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-for-biotech-companies', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/how-to-get-100-replies-cold-email', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-for-cybersecurity-companies', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/b2b-account-based-marketing-cold-email', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-for-fintech-companies', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/how-to-set-up-email-sending-infrastructure', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-for-proptech-companies', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/b2b-sales-outreach-playbook-2026', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-for-cleantech-companies', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/how-to-close-deals-cold-email-2026', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-for-edtech-companies', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/b2b-cold-email-roi-calculator-guide', lastModified: new Date() },
];

const blogPosts9: MetadataRoute.Sitemap = [
  { url: 'https://blog.becgrowth.com/blog/cold-email-for-legaltech-companies', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/how-to-write-cold-email-for-agencies', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-for-hr-tech-companies', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/b2b-cold-email-statistics-2026', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-for-martech-companies', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/how-to-use-hunter-io-cold-email', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-for-adtech-companies', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/b2b-outbound-sales-statistics-2026', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-for-insurtech-companies', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/how-to-qualify-leads-cold-email', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-for-supply-chain-companies', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/b2b-cold-email-frequency-guide', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-for-logistics-tech-companies', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/how-to-handle-cold-email-objections', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-for-data-analytics-companies', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/b2b-cold-email-glossary-2026', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-for-cloud-computing-companies', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/how-to-write-cold-email-breakup-message', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-for-ai-companies', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/b2b-cold-email-faq-2026', lastModified: new Date() },
];

const blogPosts10: MetadataRoute.Sitemap = [
  { url: 'https://blog.becgrowth.com/blog/cold-email-for-blockchain-companies', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/how-to-use-zoominfo-cold-email', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-for-gaming-companies', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/b2b-cold-email-industry-report-2026', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-for-media-production-companies', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/how-to-automate-cold-email-outreach', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-for-creative-agencies', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/b2b-cold-email-templates-2026', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-for-growth-agencies', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/how-to-do-cold-email-outreach-2026', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-for-performance-marketing-agencies', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/b2b-cold-email-best-practices-2026', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-for-seo-agencies', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/how-to-get-meetings-cold-email-2026', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-for-ppc-agencies', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/b2b-cold-email-conversion-rate-guide', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-for-social-media-agencies', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/how-to-write-cold-email-that-converts', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/cold-email-for-content-marketing-agencies', lastModified: new Date() },
  { url: 'https://blog.becgrowth.com/blog/b2b-cold-email-complete-guide-2026', lastModified: new Date() },
];

export default function sitemap(): MetadataRoute.Sitemap {
  return [
    ...staticPages,
    ...blogPosts1,
    ...blogPosts2,
    ...blogPosts3,
    ...blogPosts4,
    ...blogPosts5,
    ...blogPosts6,
    ...blogPosts7,
    ...blogPosts8,
    ...blogPosts9,
    ...blogPosts10,
  ];
}